name: weather_forecast
description: Um projeto para previsão do tempo utilizando a OpenWeatherAPI
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  lottie: ^2.2.0
  provider: ^6.0.5
  smooth_page_indicator: ^1.0.1
  mockito: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

# Flutter packages.
flutter:
  uses-material-design: true

# Assets
  assets:
    - assets/animations/clouds_animation.json
    - assets/animations/mist_animation.json
    - assets/animations/moon_animation.json
    - assets/animations/not_found_animation.json
    - assets/animations/rain_animation.json
    - assets/animations/snow_animation.json
    - assets/animations/sun_animation.json
    - assets/animations/thunderstorm_animation.json

# Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
