// Mocks generated by Mockito 5.3.2 from annotations
// in weather_forecast/services/weather_forecast_api_service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:weather_forecast/models/weather_model.dart' as _i4;
import 'package:weather_forecast/services/weather_forecast_api_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WeatherForecastApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherForecastApiService extends _i1.Mock
    implements _i2.WeatherForecastApiService {
  MockWeatherForecastApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.WeatherModel>?> getWeatherForecast(String? location) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeatherForecast,
          [location],
        ),
        returnValue: _i3.Future<List<_i4.WeatherModel>?>.value(),
      ) as _i3.Future<List<_i4.WeatherModel>?>);
}
